// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/dushixiang/pika/internal/config"
	"github.com/dushixiang/pika/internal/handler"
	"github.com/dushixiang/pika/internal/service"
	"github.com/dushixiang/pika/internal/vmclient"
	"github.com/dushixiang/pika/internal/websocket"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(logger *zap.Logger, db *gorm.DB, cfg *config.AppConfig) (*AppComponents, error) {
	userService := service.NewUserService(logger, cfg)
	oidcService := service.NewOIDCService(logger, cfg)
	gitHubOAuthService := service.NewGitHubOAuthService(logger, cfg)
	accountService := service.NewAccountService(logger, userService, oidcService, gitHubOAuthService, cfg)
	accountHandler := handler.NewAccountHandler(accountService)
	apiKeyService := service.NewApiKeyService(logger, db)
	propertyService := service.NewPropertyService(logger, db)
	trafficService := service.NewTrafficService(logger, db)
	vmClient := provideVMClient(cfg, logger)
	metricService := service.NewMetricService(logger, db, propertyService, trafficService, vmClient)
	geoIPService, err := service.NewGeoIPService(logger, cfg)
	if err != nil {
		return nil, err
	}
	agentService := service.NewAgentService(logger, db, apiKeyService, metricService, geoIPService)
	manager := websocket.NewManager(logger)
	monitorService := service.NewMonitorService(logger, db, metricService, manager)
	tamperService := service.NewTamperService(logger, db, manager)
	ddnsService := service.NewDDNSService(logger, db, propertyService, manager)
	sshLoginService := service.NewSSHLoginService(logger, db, manager, geoIPService)
	agentHandler := handler.NewAgentHandler(logger, agentService, trafficService, metricService, monitorService, tamperService, ddnsService, sshLoginService, manager)
	apiKeyHandler := handler.NewApiKeyHandler(logger, apiKeyService)
	notifier := service.NewNotifier(logger)
	alertService := service.NewAlertService(logger, db, propertyService, monitorService, notifier)
	alertHandler := handler.NewAlertHandler(logger, alertService)
	propertyHandler := handler.NewPropertyHandler(logger, propertyService, notifier)
	monitorHandler := handler.NewMonitorHandler(logger, monitorService, metricService, agentService)
	tamperHandler := handler.NewTamperHandler(logger, tamperService)
	dnsProviderHandler := handler.NewDNSProviderHandler(logger, propertyService)
	ddnsHandler := handler.NewDDNSHandler(logger, ddnsService)
	sshLoginHandler := handler.NewSSHLoginHandler(logger, sshLoginService)
	appComponents := &AppComponents{
		AccountHandler:     accountHandler,
		AgentHandler:       agentHandler,
		ApiKeyHandler:      apiKeyHandler,
		AlertHandler:       alertHandler,
		PropertyHandler:    propertyHandler,
		MonitorHandler:     monitorHandler,
		TamperHandler:      tamperHandler,
		DNSProviderHandler: dnsProviderHandler,
		DDNSHandler:        ddnsHandler,
		SSHLoginHandler:    sshLoginHandler,
		AgentService:       agentService,
		TrafficService:     trafficService,
		MetricService:      metricService,
		AlertService:       alertService,
		PropertyService:    propertyService,
		MonitorService:     monitorService,
		ApiKeyService:      apiKeyService,
		TamperService:      tamperService,
		DDNSService:        ddnsService,
		SSHLoginService:    sshLoginService,
		WSManager:          manager,
		VMClient:           vmClient,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents 应用组件
type AppComponents struct {
	AccountHandler     *handler.AccountHandler
	AgentHandler       *handler.AgentHandler
	ApiKeyHandler      *handler.ApiKeyHandler
	AlertHandler       *handler.AlertHandler
	PropertyHandler    *handler.PropertyHandler
	MonitorHandler     *handler.MonitorHandler
	TamperHandler      *handler.TamperHandler
	DNSProviderHandler *handler.DNSProviderHandler
	DDNSHandler        *handler.DDNSHandler
	SSHLoginHandler    *handler.SSHLoginHandler

	AgentService    *service.AgentService
	TrafficService  *service.TrafficService
	MetricService   *service.MetricService
	AlertService    *service.AlertService
	PropertyService *service.PropertyService
	MonitorService  *service.MonitorService
	ApiKeyService   *service.ApiKeyService
	TamperService   *service.TamperService
	DDNSService     *service.DDNSService
	SSHLoginService *service.SSHLoginService

	WSManager *websocket.Manager
	VMClient  *vmclient.VMClient
}

// provideVMClient 提供 VictoriaMetrics 客户端
func provideVMClient(cfg *config.AppConfig, logger *zap.Logger) *vmclient.VMClient {

	if cfg.VictoriaMetrics == nil || !cfg.VictoriaMetrics.Enabled {
		logger.Info("VictoriaMetrics is not enabled, using default configuration")

		return vmclient.NewVMClient("http://localhost:8428", 30*time.Second, 60*time.Second)
	}

	writeTimeout := time.Duration(cfg.VictoriaMetrics.WriteTimeout) * time.Second
	if writeTimeout == 0 {
		writeTimeout = 30 * time.Second
	}

	queryTimeout := time.Duration(cfg.VictoriaMetrics.QueryTimeout) * time.Second
	if queryTimeout == 0 {
		queryTimeout = 60 * time.Second
	}

	logger.Info("VictoriaMetrics client initialized", zap.String("url", cfg.VictoriaMetrics.URL), zap.Duration("writeTimeout", writeTimeout), zap.Duration("queryTimeout", queryTimeout))

	return vmclient.NewVMClient(cfg.VictoriaMetrics.URL, writeTimeout, queryTimeout)
}
